typography_spectrum: 0.10469662747345865
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.05130884563550353
  lightness: 0.4349843277595937
  saturation: 0.4458718129899353
  rhythmicContrast: 0.35426028072834015
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.14650856843218207
analytics:
  google: null
  facebook: null
  twitter: null
name: itsit
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ARC Design
    url: 'http://arc-design.com'
    type: external
favicon: null
purpose: []
